services:
  top_albums_database:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  top_albums_app:
    image: top_albums_app
    entrypoint: ./entrypoint.sh
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - top_albums_database

volumes:
  pgdata: