"""Add fiel playing on albums

Revision ID: b3b5861c5f20
Revises: f0ab2aeba0d8
Create Date: 2024-07-31 15:21:24.933847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b5861c5f20'
down_revision: Union[str, None] = 'f0ab2aeba0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('playing', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'playing')
    # ### end Alembic commands ###
